version: "3.9"
services:
  cloutapis:
    build: .
    command: sh -c "./scripts/wait-for.sh db-cloutapis:5432 -- yarn dev"
    container_name: cloutapis
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      NODE_ENV: development
      HTTP_PORT: 5000
      DEBUG_PORT: 5001
      DB_HOST: db-cloutapis
      DB_USERNAME: cloutapis
      DB_PASSWORD: cloutapis
      BONSAI_URL: "elasticsearch-cloutapis:9200"
    restart: unless-stopped
    volumes:
      - .:/app/
    depends_on:
      - db-cloutapis
      - elasticsearch-cloutapis
    networks:
      - cloutapis

  cloutapis-worker:
    build: .
    command: sh -c "./scripts/wait-for.sh db-cloutapis:5432 -- yarn dev-worker"
    container_name: cloutapis-worker
    environment:
      NODE_ENV: development
      DB_HOST: db-cloutapis
      DB_USERNAME: cloutapis
      DB_PASSWORD: cloutapis
      BONSAI_URL: "elasticsearch-cloutapis:9200"
    restart: unless-stopped
    volumes:
      - .:/app/
    depends_on:
      - db-cloutapis
      - elasticsearch-cloutapis
    networks:
      - cloutapis

  db-cloutapis:
    image: postgres:13.3
    container_name: db-cloutapis
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cloutapis
      - POSTGRES_PASSWORD=cloutapis
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - cloutapis

  elasticsearch-cloutapis:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: es01
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      - cluster.name=es-cloutapis-cluster
      - cluster.initial_master_nodes=es01
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: unless-stopped
    networks:
      - cloutapis

volumes:
  postgres-data:
    driver: local
  elasticsearch-data:
    driver: local

networks:
  cloutapis:
    driver: bridge
